version: '3'
services:
  #PHP Service
  webphp:
    build:
      context: .
      dockerfile: Dockerfile
    image: webgis-php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php:/usr/local/etc/php/conf.d

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

#Docker Networks
networks:
  default:
    external:
      name: web-gis-docker_app-network
